## workflow build config

# id and name for the workflow (bundle id = domain.id)
id: alfred-text-tokenizer-workflow

# base domain
domain: com.tumblr.ramiroaraujo

name: Tokenize
description: Text-expander workflow for converting between several text lists syntax into several others
created_by: Ramiro Araujo
website: https://github.com/ramiroaraujo/alfred-text-tokenizer-workflow
readme: readme

## development config

# path is the relative path to the workflow in the project root
path: workflow

# If you are using Alfred's advanced Dropbox sync, indicate the path shown in
# Alfred Preferences > Advanced > Syncing:
dropbox: ~/Dropbox